"""IX-BlackFox-WorldTwin public API.

IX-BlackFox-WorldTwin is a source-available governed world-model evidence layer
for AI-agent decisions.

The current public API exports stable project metadata, doctrine boundaries,
typed world-state contracts, evidence reference contracts, uncertainty
contracts, scenario manifest contracts, and scenario validation gates. Later
Wave 1 commits will add assumption ledgers, constraint checks, deterministic
simulation, branching predictions, receipts, reality-delta scoring,
model-confidence tracking, adaptation gates, and human-reviewable handoff
packages without weakening this package boundary.
"""

from ix_blackfox_worldtwin.doctrine import (
    CANONICAL_DOCTRINE,
    CLAIM_BOUNDARY_RULES,
    TRIAD_ROLES,
    WORLD_TWIN_FOUNDATIONAL_RULES,
    ClaimBoundaryRule,
    ClaimBoundaryViolation,
    SystemRole,
    find_claim_boundary_violations,
    get_claim_boundary_rules,
    get_triad_roles,
    get_worldtwin_foundational_rules,
    is_claim_language_allowed,
    render_doctrine_summary,
)
from ix_blackfox_worldtwin.evidence import (
    EVIDENCE_ID_DIGEST_LENGTH,
    EVIDENCE_SCHEMA_VERSION,
    SHA256_HEX_LENGTH,
    EvidenceAttribute,
    EvidenceKind,
    EvidenceReference,
    create_evidence_reference,
    create_evidence_reference_from_hash,
    hash_evidence_content,
    make_evidence_id,
)
from ix_blackfox_worldtwin.metadata import (
    CORE_DOCTRINE,
    DESCRIPTION_FORBIDDEN_TERMS,
    FOUNDATIONAL_LAW,
    GITHUB_DESCRIPTION,
    GITHUB_DESCRIPTION_LIMIT,
    GITHUB_TOPICS,
    LICENSE_NAME,
    PACKAGE_NAME,
    PROHIBITED_CLAIMS,
    PROJECT_NAME,
    PUBLIC_DESCRIPTION,
    REPOSITORY_URL,
    RESEARCH_STATUS,
    VERSION,
    PackageIdentity,
    get_external_description_issues,
    get_github_description,
    get_github_topics,
    get_package_identity,
    is_prohibited_claim,
)
from ix_blackfox_worldtwin.scenario import (
    SCENARIO_ID_DIGEST_LENGTH,
    SCENARIO_SCHEMA_VERSION,
    MeasurableOutput,
    ScenarioBoundary,
    ScenarioBoundaryKind,
    ScenarioManifest,
    ScenarioVariable,
    ScenarioVariableKind,
    create_scenario_manifest,
    make_scenario_id,
)
from ix_blackfox_worldtwin.scenario_validation import (
    ScenarioValidationIssue,
    ScenarioValidationResult,
    ScenarioValidationSeverity,
    ensure_scenario_manifest_replayable,
    validate_scenario_manifest,
)
from ix_blackfox_worldtwin.state import (
    STATE_ID_DIGEST_LENGTH,
    STATE_SCHEMA_VERSION,
    StateDimension,
    WorldState,
    WorldStateKind,
    create_observed_state,
    create_predicted_state,
    create_simulated_state,
    create_world_state,
    make_state_id,
)
from ix_blackfox_worldtwin.uncertainty import (
    CONFIDENCE_DIGEST_LENGTH,
    CONFIDENCE_MAX,
    CONFIDENCE_MIN,
    UNCERTAINTY_SCHEMA_VERSION,
    ConfidenceAssessment,
    ConfidenceTier,
    UncertaintyBand,
    UncertaintySource,
    classify_confidence,
    combine_confidence_conservatively,
    create_confidence_assessment,
    make_confidence_assessment_id,
    validate_confidence,
)

__all__ = [
    "CANONICAL_DOCTRINE",
    "CLAIM_BOUNDARY_RULES",
    "CONFIDENCE_DIGEST_LENGTH",
    "CONFIDENCE_MAX",
    "CONFIDENCE_MIN",
    "CORE_DOCTRINE",
    "DESCRIPTION_FORBIDDEN_TERMS",
    "EVIDENCE_ID_DIGEST_LENGTH",
    "EVIDENCE_SCHEMA_VERSION",
    "FOUNDATIONAL_LAW",
    "GITHUB_DESCRIPTION",
    "GITHUB_DESCRIPTION_LIMIT",
    "GITHUB_TOPICS",
    "LICENSE_NAME",
    "PACKAGE_NAME",
    "PROHIBITED_CLAIMS",
    "PROJECT_NAME",
    "PUBLIC_DESCRIPTION",
    "REPOSITORY_URL",
    "RESEARCH_STATUS",
    "SCENARIO_ID_DIGEST_LENGTH",
    "SCENARIO_SCHEMA_VERSION",
    "SHA256_HEX_LENGTH",
    "STATE_ID_DIGEST_LENGTH",
    "STATE_SCHEMA_VERSION",
    "TRIAD_ROLES",
    "UNCERTAINTY_SCHEMA_VERSION",
    "VERSION",
    "WORLD_TWIN_FOUNDATIONAL_RULES",
    "ClaimBoundaryRule",
    "ClaimBoundaryViolation",
    "ConfidenceAssessment",
    "ConfidenceTier",
    "EvidenceAttribute",
    "EvidenceKind",
    "EvidenceReference",
    "MeasurableOutput",
    "PackageIdentity",
    "ScenarioBoundary",
    "ScenarioBoundaryKind",
    "ScenarioManifest",
    "ScenarioValidationIssue",
    "ScenarioValidationResult",
    "ScenarioValidationSeverity",
    "ScenarioVariable",
    "ScenarioVariableKind",
    "StateDimension",
    "SystemRole",
    "UncertaintyBand",
    "UncertaintySource",
    "WorldState",
    "WorldStateKind",
    "classify_confidence",
    "combine_confidence_conservatively",
    "create_confidence_assessment",
    "create_evidence_reference",
    "create_evidence_reference_from_hash",
    "create_observed_state",
    "create_predicted_state",
    "create_scenario_manifest",
    "create_simulated_state",
    "create_world_state",
    "ensure_scenario_manifest_replayable",
    "find_claim_boundary_violations",
    "get_claim_boundary_rules",
    "get_external_description_issues",
    "get_github_description",
    "get_github_topics",
    "get_package_identity",
    "get_triad_roles",
    "get_worldtwin_foundational_rules",
    "hash_evidence_content",
    "is_claim_language_allowed",
    "is_prohibited_claim",
    "make_confidence_assessment_id",
    "make_evidence_id",
    "make_scenario_id",
    "make_state_id",
    "render_doctrine_summary",
    "validate_confidence",
    "validate_scenario_manifest",
]
